/** 修改这里即可替换双语祝福、同学、音乐与视频。 */
// GitHub Pages 项目站点会部署在 /仓库名/ 下；本地开发时保持空前缀。
const basePath = (process.env.NEXT_PUBLIC_BASE_PATH ?? '').replace(/\/$/, '');
const asset = (path) => `${basePath}${path}`;

const config = {
  emojis: [
    '🐯',
    '🦌',
    '🐙',
    '🐟',
    '🐱',
    '🐻',
    '☀️',
    '🐷',
    '😀',
    '😄',
    '😆',
    '😊',
    '😎',
    '🤓',
    '🥳',
    '😋',
    '🤭',
    '🥹',
    '😁',
    '😇',
    '🙂',
    '😜',
    '🤗',
    '🫡',
    '😺',
  ],
  music: {
    src: asset('/audio/top-of-the-world.mp3'),
    title: 'Top Of The World',
    artist: 'Carpenters',
    album: 'A Song for You',
    cover: asset('/images/a-song-for-you.jpg'),
    loop: true,
    volume: 0.45,
    videoDuckVolume: 0.1,
  },
  video: {
    src: 'https://ik.imagekit.io/1fwccoblm/Untitled.mp4',
    autoplay: false,
    muted: false,
  },
  artwork: {
    card: asset('/images/teachers-day-card.png'),
    hallway: asset('/images/hallway.png'),
    door: asset('/images/door.png'),
    envelope: asset('/images/envelope.png'),
  },
  gift: {
    artwork: asset('/images/jujube-gift.png'),
    model: asset('/models/hongzao-red-date.glb'),
  },
  locales: {
    zh: {
      teacher: { name: '老师', doorSign: '教师办公室' },
      gift: {
        seal: '枣礼',
        kicker: '一盒红枣 · 三重心意',
        intro: '一盒红枣，敬一份师恩',
        open: '开启这份心意',
        opening: '枣香盈盒，心意已至。',
        modelLabel: '旋转展示的红枣',
        pauseRotation: '暂停旋转',
        resumeRotation: '继续旋转',
        loading: '红枣正在慢慢浮起…',
        unavailable: '先看看这盒红枣，心意一样在。',
        steps: [
          {
            chapter: '第一愿 · 求学有成',
            title: '一颗红枣，一份期许',
            text: '在“束脩六礼”的寓意中，红枣取“枣”与“早”的谐音，寄托“早日高中、学有所成”的期许。小小一颗枣，装着认真求学的心意。',
            cta: '这一份期许，我们记得',
          },
          {
            chapter: '第二意 · 不忘师恩',
            title: '您的期许，我们记得',
            text: '把这盒红枣送给您，也是在说：您的教导和期待，我们都放在心上。我们会带着这份心意，好好学习，慢慢成长。',
            cta: '也愿您的日子甜一点',
          },
          {
            chapter: '第三愿 · 岁岁安然',
            title: '也愿您的日子，甜一点',
            text: '这一回，我们还想把“早”的祝愿送给您：愿您忙碌过后，早些休息；愿讲台之外，也有自己的轻松和快乐。谢谢您，老师。💛',
            cta: '启封 · 读一封全班的信',
          },
        ],
      },
      story: {
        knockingText: '办公室门外似乎有人……',
        knock: '咚',
        firstChoice: { open: '开门', refuse: '没人在办公室' },
        refuseText: '不对，谁在说话？有人在里面！',
        secondChoice: { open: '开门', refuse: '真的没人在里面' },
        autoOpen: ['那好，我们明天再来。', '……', '咔哒。', '门自己开了。'],
        envelopeIntro: '我们有东西想送给您。',
        swipeHint: '向上抽出视频，立即播放',
        videoHint: '先把这份惊喜送给您',
        surprise: '老师，教师节快乐！',
        opening: '是谁在门外呢？',
        waiting: '今天，有一份特别的心意。',
      },
      letter: {
        greeting: '亲爱的老师：',
        paragraphs: [
          '学生和老师每天见面，好像很平常。上课、下课、作业、考试，一天天过去，很容易让人觉得这些都是理所当然的。',
          '但仔细想想，能在成长最快、也最容易迷茫的几年里，遇到愿意认真教我们、也认真对待我们的老师，其实是一件很幸运的事。',
          '以后我们可能会忘记考试分数，但您耐心的讲解，还有那些您认真陪着我们走过的日子，我们会一直记得。',
          '谢谢您的认真，也谢谢您的耐心。',
          '祝您教师节快乐，也希望在讲台之外，也一直有属于自己的轻松和快乐。',
        ],
        signature: '—— 全班同学',
      },
      ui: {
        title: '叩叩，老师在吗？',
        pageTitle: '叩叩，老师在吗？ · 教师节快乐',
        brand: '教师节快乐',
        eyebrow: '九月十日 · 一份小小的心意',
        loading: '正在准备一份小惊喜…',
        slow: '小惊喜还在路上，再等一下就好。',
        retry: '重新加载',
        soundNote: '有敲门声，还有一首想送给您的歌。',
        enable: '开启声音进入',
        silent: '静音进入',
        later: '随时可以点击右上角唱片，开关音乐。',
        musicError: '音乐暂时没有准备好，可以先静音进入。',
        artError: '场景没有加载成功，请重试。',
        continueSilent: '先静音进入',
        play: '播放音乐',
        pause: '暂停音乐',
        armed: '开门后播放',
        disarmed: '音乐已关闭',
        blocked: '点击播放',
        openLetter: '也可以点这里播放视频',
        letterTo: '致亲爱的老师',
        videoError: '视频暂时无法播放，请稍后再试。',
        videoLabel: '送给老师的祝福视频',
        videoPlay: '点击播放这份惊喜',
        videoLoading: '正在打开这份惊喜…',
        videoSlow: '视频还在路上，可以重试，或先看看另一份礼物。',
        videoThenLetter: '看完，还有一封写给您的信。',
        videoContinue: '先看看另一份礼物',
        replay: '再收一次祝福',
        footer: '每一份耐心，我们都记得。',
        letterLabel: '写给老师的一封信',
        ready: '准备好了吗？',
        language: '选择语言',
        musicWaiting: '视频播放中，背景音乐已调低',
        from: '来自我们所有人',
        loadLabel: '正在加载祝福',
        celebration: '教师节快乐！',
        achievementUnlocked: '达成成就：',
        achievementEmptyOffice: '此地无银三百两',
        landingSound: '开启声音，体验会更完整',
        landingDate: '教师节 · 九月十日',
        landingLoading: '正在准备这份心意',
        landingStart: '点击任意位置开始',
        landingChoose: '请选择进入方式',
        cardOpen: '轻触打开贺卡',
        cardOpening: '祝福正在展开…',
        cardInside: '老师，教师节快乐！',
      },
    },
    en: {
      teacher: { name: 'Teacher', doorSign: 'Teachers’ Office' },
      gift: {
        seal: 'GIFT',
        kicker: 'RED DATES · THREE WISHES',
        intro: 'A box of red dates, with all our thanks',
        open: 'Open this gift',
        opening: 'A little sweetness, carrying all our thanks.',
        modelLabel: 'Red dates in a rotating 3D view',
        pauseRotation: 'Pause rotation',
        resumeRotation: 'Resume rotation',
        loading: 'Your red dates are on their way…',
        unavailable: 'The gift is still here, along with all our thanks.',
        steps: [
          {
            chapter: 'FIRST WISH · LEARNING',
            title: 'A small fruit, a hopeful wish',
            text: 'Among the symbolic gifts of the Shuxiu tradition, red dates express a wish for success in learning. The Chinese word for date, zǎo, sounds like “early”: a little wish that effort will bear fruit soon.',
            cta: 'We remember this wish',
          },
          {
            chapter: 'SECOND THOUGHT · GRATITUDE',
            title: 'We remember your hopes for us',
            text: 'This box is also our way of saying that we hold your care and encouragement close. We will keep learning, keep trying, and grow into the people you believe we can become.',
            cta: 'A sweeter wish for you',
          },
          {
            chapter: 'THIRD WISH · EASE AND JOY',
            title: 'May your days be a little sweeter',
            text: 'This time, we wish something “early” for you too: an earlier rest after a busy day, and time beyond the classroom for your own ease and joy. Thank you, Teacher. 💛',
            cta: 'Unseal · Read our letter',
          },
        ],
      },
      story: {
        knockingText: 'There seems to be someone at the door…',
        knock: 'Knock',
        firstChoice: {
          open: 'Open the door',
          refuse: 'No one is in the office',
        },
        refuseText: 'Wait—who just said that? Someone is inside!',
        secondChoice: {
          open: 'Open the door',
          refuse: 'There really is no one inside',
        },
        autoOpen: [
          'All right, we’ll come back tomorrow.',
          '…',
          'Click.',
          'The door opens all by itself.',
        ],
        envelopeIntro: 'We have something for you.',
        swipeHint: 'Pull up the video to play it',
        videoHint: 'A little surprise, just for you',
        surprise: 'Happy Teachers’ Day!',
        opening: 'Who could it be?',
        waiting: 'A little something, just for you.',
      },
      letter: {
        greeting: 'Dear Teacher,',
        paragraphs: [
          'Students and teachers see each other every day, so it can all seem quite ordinary. Classes, breaks, homework, and exams pass one after another, and it is easy to take them for granted. ',
          'But when we think about it, meeting a teacher who teaches us with care and takes us seriously during the years when we grow the fastest and feel most uncertain is a real piece of good fortune. ',
          'We may forget our exam scores one day, but we will always remember your patient explanations and the days you carefully walked alongside us. ',
          'Thank you for your dedication, and thank you for your patience. ',
          'Happy Teachers’ Day. We also hope that beyond the classroom, you always have time for ease and joy of your own. ',
        ],
        signature: '— The whole class',
      },
      ui: {
        title: 'Knock, knock. Anyone there?',
        pageTitle: 'Knock, knock · Happy Teachers’ Day',
        brand: 'Happy Teachers’ Day',
        eyebrow: 'SEPTEMBER 10 · A LITTLE THANK-YOU',
        loading: 'Getting a little surprise ready…',
        slow: 'Our little surprise is taking a moment.',
        retry: 'Try again',
        soundNote: 'A little knock, and a song we picked for you.',
        enable: 'Enter with sound',
        silent: 'Enter quietly',
        later: 'Tap the record in the corner to turn music on or off.',
        musicError: 'The music isn’t ready yet. You can enter quietly.',
        artError: 'The scene couldn’t load. Please try again.',
        continueSilent: 'Continue quietly',
        play: 'Play music',
        pause: 'Pause music',
        armed: 'Music starts when the door opens',
        disarmed: 'Music is off',
        blocked: 'Tap to play',
        openLetter: 'Or tap here to play the video',
        letterTo: 'For our dear teacher',
        videoError: 'The video couldn’t play. Please try again later.',
        videoLabel: 'A video for our teacher',
        videoPlay: 'Play your surprise',
        videoLoading: 'Opening your surprise…',
        videoSlow:
          'The video is taking a while. Try again, or open your other gift.',
        videoThenLetter: 'A letter is waiting when the video ends.',
        videoContinue: 'See your other gift',
        replay: 'Open your surprise again',
        footer: 'We remember every little act of kindness.',
        letterLabel: 'A letter for our teacher',
        ready: 'Ready for a little surprise?',
        language: 'Choose language',
        musicWaiting: 'Background music lowered for the video',
        from: 'From all of us',
        loadLabel: 'Loading your greeting',
        celebration: 'Happy Teachers’ Day!',
        achievementUnlocked: 'Achievement unlocked:',
        achievementEmptyOffice: 'Nothing suspicious here',
        landingSound: 'Enable sound for a fuller experience',
        landingDate: 'Teachers’ Day · September 10',
        landingLoading: 'Preparing something for you',
        landingStart: 'Click anywhere to start',
        landingChoose: 'Choose how to enter',
        cardOpen: 'Tap to open the card',
        cardOpening: 'Unfolding your greeting…',
        cardInside: 'Happy Teachers’ Day!',
      },
    },
  },
};
export default config;
